interface Props {
  variant: 'first-run' | 'no-results';
}

const FEATURE_CARDS = [
  { icon: '🌍', title: 'Any Destination', desc: 'From Tokyo to Timbuktu — any city, state or country' },
  { icon: '🤖', title: 'AI-Powered', desc: 'Day-by-day plans generated by a large language model' },
  { icon: '✏️', title: 'Fully Editable', desc: 'Reorder, remove, and customize every stop' },
];

export function EmptyState({ variant }: Props) {
  if (variant === 'no-results') {
    return (
      <div
        className="rise glass"
        style={{ borderRadius: '20px', padding: '40px 28px', textAlign: 'center', maxWidth: '480px', margin: '0 auto' }}
      >
        <p aria-hidden="true" style={{ fontSize: '3rem' }}>🗺️</p>
        <h2 style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--ink)', marginTop: '12px' }}>
          No itinerary came back
        </h2>
        <p style={{ fontSize: '0.875rem', color: 'var(--muted)', marginTop: '8px', lineHeight: 1.6 }}>
          Try adding a destination and a number of days — e.g.{' '}
          <em>"4 days in Rome, first visit"</em>.
        </p>
      </div>
    );
  }

  return (
    <div className="rise" style={{ textAlign: 'center', padding: '16px 0 40px' }}>
      {/* Feature Cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '16px',
        marginTop: '8px',
      }}>
        {FEATURE_CARDS.map(({ icon, title, desc }) => (
          <div
            key={title}
            className="glass glass-hover"
            style={{
              borderRadius: '16px',
              padding: '20px 18px',
              textAlign: 'left',
            }}
          >
            <span style={{ fontSize: '1.8rem', display: 'block', marginBottom: '10px' }}>{icon}</span>
            <p style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--ink)', margin: '0 0 4px' }}>{title}</p>
            <p style={{ fontSize: '0.78rem', color: 'var(--muted)', margin: 0, lineHeight: 1.5 }}>{desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
